language: swift
osx_image: xcode13.2
env:
  global:
  - FRAMEWORK_NAME=AWSAppSync
  - BUILD_FOLDER=./build
xcode_workspace: AWSAppSyncClient.xcworkspace
xcode_scheme: AWSAppSync
before_install:
- gem update bundler
- openssl aes-256-cbc -K $encrypted_6919a533707f_key -iv $encrypted_6919a533707f_iv
  -in AWSAppSyncIntegrationTests/appsync_test_credentials.json.enc
  -out AWSAppSyncIntegrationTests/appsync_test_credentials.json
  -d
- brew update
- brew outdated carthage || brew upgrade carthage

before_deploy:
- bash ./build-support/carthage-build.sh build --no-skip-current
- bash ./build-support/carthage-build.sh archive $FRAMEWORK_NAME
- bash ./build-support/build-xcframeworks.sh $FRAMEWORK_NAME
script:
- xcodebuild -quiet -workspace AWSAppSyncClient.xcworkspace -scheme AWSAppSync build test -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest'
deploy:
- provider: releases
  api_key:
    secure: "eI3j9dDKsoUp52E6MN5yuvyCV3dM3ihCjR/rBTvkvlAK6s9sBiIC/sRy+5eL/gjJgpvkxRUsfQsSzI5FSyrj9ydjuvqkK67aXvOQ1a9FHa7uR6/9U47NgY3ExU0F6quNdTDlJfc0HGB0ljgWHdVkz3U9zQBXpV92k1AqMq5DkjtZNAJW2I9MEcQclW3Gr7bCYhlq4zFLF5ThCRSbHFK58KL2aN4dtJ5kg8lxZv3q4AyjFwQScA92WDb+jT/cez8g7Qxm7kXBbjgGf4yF3lW+3BulEKCRZWsOBtR7SYfqIJv11dreOZ6UfcA1fkWb7kj1WnsWEszgvPZS9eLi/kOLd700dTsOT/Lo16CYXoq/hDj9H5nPZkZ+3Er1gsF2wECooT6s5e4gNPIVL6BKrJljajkLU21zunP5S6ukuh4WskySu0HT3gNN/TMoXXe2UR350Uc03mh6qLoT6krBBV3yFdWxYyrQvkqzTf/b/oguNAp4mQjfK/ONyNkhdJ0o4NW1IEm1quKfIMywxng7ph11S57l0fbriNGDLZRQpNUaseFZCO7OekOJdAgF2tVIKjnK49JpOKocPEOGNaiiiuVrJd9IX/vaDUJo4jkl7FfzxBjNKTjqEDHkXuJsJ9xfIII2i8RcxEzCFPIYWROv9f35zf5W75Q9UDMA0atZ44pgniE="
  file:
    - "$FRAMEWORK_NAME.framework.zip"
    - "$BUILD_FOLDER/$FRAMEWORK_NAME.xcframework.zip"
  skip_cleanup: true
  on:
   repo: awslabs/aws-mobile-appsync-sdk-ios
   tags: true
- provider: script
  script: bash ./build-support/cocoapods_release.sh
  on:
    repo: awslabs/aws-mobile-appsync-sdk-ios
    tags: true
